export enum LeaveRequestType {
  PAID = 'PAID',
  UNPAID = 'UNPAID',
}

export enum LeaveRequestStage {
  REGIONAL_REVIEW = 'REGIONAL_REVIEW',
  AREA_REVIEW = 'AREA_REVIEW',
  HR_REVIEW = 'HR_REVIEW',
  DIRECTOR_REVIEW = 'DIRECTOR_REVIEW',
  COMPLETED = 'COMPLETED',
}

export enum LeaveReasonType {
  DEATH = 'DEATH',
  EXTENDED_DEATH = 'EXTENDED_DEATH',
  MARRIAGE = 'MARRIAGE',
  UNION_EVENT = 'UNION_EVENT',
  PERSONAL = 'PERSONAL',
  IHSS = 'IHSS',
  STUDY = 'STUDY',
  COURT_APPEARANCE = 'COURT_APPEARANCE',
  CALAMITY = 'CALAMITY',
  FAMILY_CARE = 'FAMILY_CARE',
  OFFICIAL_COMMISSION = 'OFFICIAL_COMMISSION',
  OTHER_JUSTIFIED = 'OTHER_JUSTIFIED',
}

export enum LeaveMarriageType {
  FIRST = 'FIRST',
  SUBSEQUENT = 'SUBSEQUENT',
}

export enum LeaveRelationship {
  SELF = 'SELF',
  FATHER = 'FATHER',
  MOTHER = 'MOTHER',
  SON = 'SON',
  DAUGHTER = 'DAUGHTER',
  BROTHER = 'BROTHER',
  SISTER = 'SISTER',
  SPOUSE = 'SPOUSE',
  PARTNER = 'PARTNER',
}

export enum LeaveRequestStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}
