export enum EmployeeJobActionType {
  MODALITY_CHANGE = 'MODALITY_CHANGE',
  STATUS_CHANGE = 'STATUS_CHANGE',
  AREA_CHANGE = 'AREA_CHANGE',
  POSITION_CHANGE = 'POSITION_CHANGE',
  UNPAID_LEAVE = 'UNPAID_LEAVE',
}
