// vacation.enums.ts

export enum VacationAccrualType {
  YEARLY = 'YEARLY', //ANUAL
  MONTHLY = 'MONTHLY', //MENSUAL
}

export enum VacationPeriodStatus {
  PENDING = 'PENDING', //PENDIENTE
  AVAILABLE = 'AVAILABLE', //DISPONIBLE
  CLOSED = 'CLOSED', //CERRADO
  EXPIRED = 'EXPIRED', //CADUCADO
}

export enum VacationRequestStatus {
  PENDING = 'PENDING', // PENDIENTE
  APPROVED = 'APPROVED', // APROBADO
  REJECTED = 'REJECTED', // RECHAZADO
  ADJUSTED = 'ADJUSTED', // AJUSTADO
  CANCELLED = 'CANCELLED', // CANCELADO
}

export enum VacationMovementType {
  EARNED = 'EARNED', //GANADO
  REQUEST = 'REQUEST', //SOLICITUD
  GOVERNMENT = 'GOVERNMENT', //GOBIERNO
  ADJUSTMENT = 'ADJUSTMENT', //AJUSTE
  CANCELLED = 'CANCELLED', //CANCELADO
  EXPIRED = 'EXPIRED', //EXPIRADO
  INITIAL_LOAD = 'INITIAL_LOAD',
}

export enum VacationAdjustmentType {
  GOVERNMENT_DAY = 'GOVERNMENT_DAY', //DÍA_DEL_GOBIERNO
  HR_CORRECTION = 'HR_CORRECTION', //CORRECCIÓN_RRHH
  CANCEL_REQUEST = 'CANCEL_REQUEST', //SOLICITUD_CANCELAR
}

export enum VacationRequestStage {
  BOSS_REVIEW = 'BOSS_REVIEW', // REVISION_JEFE
  HR_REVIEW = 'HR_REVIEW', // REVISION_RRHH
  COMPLETED = 'COMPLETED', // COMPLETADO
}
